databases:
  - name: grocery-db
    plan: free
    databaseName: grocery_db
    user: grocery_user

services:
  - type: web
    name: grocery-bud-app
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    # Note: Using 'djangocrud.wsgi' because that is your project folder name
    startCommand: "gunicorn djangocrud.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: grocery-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "grocery-bud-app.onrender.com"
      - key: PYTHON_VERSION
        value: "3.10.0"
